### ISSUE TITLE
[TEST] Notification

### ISSUE THREAD

**Issue by Kyalma** [CentraleFitness/oled_server#1]
Please close this.

**Comment by psyycker** [comment]
Tu t'amuse ?

**Comment by Kyalma** [comment]
J'expérimente le système d'issues.
C'est très pratique, cela permet de communiquer avec les différents membres de l'équipe 📬 , tout en gardant une trace écrite 📄 . Cette fonction peut-être utilisée comme un outil "forum" ou comme un système de ticket.
